stages:
  - test

test_go:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.19
  script:
    - go test -v ./...

test_vagrant:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/debian:bookworm-slim
  tags: [ai3]
  script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install ansible build-essential golang openssh-client
    - go build -ldflags="-extldflags=-static" -tags "sqlite_omit_load_extension netgo" ./cmd/wig
    - mkdir -p $HOME/.ssh
    - echo "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_ed25519
    - chmod 0600 $HOME/.ssh/id_ed25519
    - ssh -o StrictHostKeyChecking=no -nN -L 4949:localhost:4949 ${LIBVIRT} &
    - cd test && go run driver.go --provider=vmine --ssh-args="-o ProxyJump=${LIBVIRT}" setup.yml

