stages:
  - test

test_go:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:1.19
  script:
    - go test -v ./...

test_vagrant:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/debian:bookworm-slim
  script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install ansible golang openssh-client
    - go build ./cmd/wig
    - echo "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
    - ssh -nN -L 4949:localhost:4949 ${LIBVIRT}
    - cd test && go run driver.go --provider=vmine:http://localhost:4949 setup.yml

